"""Create test table

Revision ID: 1c7206baf4ed
Revises:
Create Date: 2026-08-14 13:00:47.307018

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1c7206baf4ed"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_order_id"), table_name="order")
    op.drop_index(op.f("ix_order_user_id"), table_name="order")
    op.drop_table("order")
    op.drop_index(op.f("ix_product_id"), table_name="product")
    op.drop_index(op.f("ix_product_name"), table_name="product")
    op.drop_table("product")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "description", sa.TEXT(), autoincrement=False, nullable=False
        ),
        sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "category_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("image_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("product_category_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("product_pkey")),
    )
    op.create_index(op.f("ix_product_name"), "product", ["name"], unique=True)
    op.create_index(op.f("ix_product_id"), "product", ["id"], unique=False)
    op.create_table(
        "order",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "product_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "quantity", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "total_price", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("order_product_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("order_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("order_pkey")),
    )
    op.create_index(
        op.f("ix_order_user_id"), "order", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_order_id"), "order", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "password_hash", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "username", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "firstname", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "is_admin",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "categories",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("slug", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("categories_pkey")),
    )
    op.create_index(
        op.f("ix_categories_slug"), "categories", ["slug"], unique=True
    )
    op.create_index(
        op.f("ix_categories_name"), "categories", ["name"], unique=True
    )
    op.create_index(
        op.f("ix_categories_id"), "categories", ["id"], unique=False
    )
    # ### end Alembic commands ###
